#Build Stage
FROM python:3.12 AS build
WORKDIR /build
COPY app/requirements.txt .
RUN pip install --prefix=/install -r requirements.txt
COPY app/ .

#Runtime Stage
FROM python:3.12-slim
WORKDIR /app
COPY --from=build /install /usr/local
COPY --from=build /build /app
EXPOSE 8080
CMD ["python", "main.py"]
